= Secured - Spring Boot Blueprint

This application exposes a simple REST API and also provides a index html page for user login.

IMPORTANT: This blueprint requires that you use link:https://access.redhat.com/products/red-hat-single-sign-on[Red Hat SSO] to issue access tokens for interacting with.

IMPORTANT: This blueprint requires Java 8 JDK or greater and Maven 3.3.x or greater.

=== To Run:

```
http:<YOUR-HOST-IP>:<PORT>/blueprint-rhsso
```

=== Path to Javascrip Adapter

https://<RHSSO-HOSTNAME>/auth/js/keycloak.js

=== RHSSO Configuration:

client configuration:

```
client-id: blueprint-endpoint
client-protocol: openid-connect
access-type: confidential
standard-flow-enabled: true
direct-access-grant-enabled: true
root-url: https://<YOUR-HOST-IP>:<PORT>
base-url: https://<YOUR-HOST-IP>:<PORT>
web-origins: *
```

create a new token mapper under blueprint-endpoint client called `github`:

```
name: github
consent-required: off
mapper-type: user attribute
user-attribute: github
token-claim-name: github
claim-json-type: string
add-to-ID-token: false
add-to-ACCESS-token: true
add-to-USER-info: true
multivalued: false
```

blueprint-endpoint client roles:

```
blueprint-admin
```

create a new user:
```
username: user1
password: user1
OBS. set temporary to: off
```

under attributes tab of the recently created user, add a new attribute called `github`
with the value `<YOUR-GITHUB-ADDRESS>`

Example:

```
key: aelkz
value: https://www.github.com/aelkz
```

user assigned roles:

```
blueprint-endpoint/blueprint-admin
```

=== TEST IT!

1. Access the API root context path. Example:

https://<host-ip>:8443/blueprint-rhsso
or
http://<host-ip>:8080/blueprint-rhsso

2. Login clicking the login button

3. Type user1/user1 for authentication

4. Done!

OBS. You may want to call using Postman with the recently acquired access token:

<header> Authorization: Bearer ...

GET https://<host-ip>:8443/blueprint-rhsso/api/greeting

or

GET http://<host-ip>:8080/blueprint-rhsso/api/greeting
